swagger: '2.0'
info:
  description: 'Avaliação Prática Lemobs'
  version: '1.0.0'
  title: Desafio API Lemobs

basePath: /v1/

consumes:
  - application/json
produces:
  - application/json

schemes:
  - http

paths:

  /aluno:
    x-swagger-router-controller: aluno
    post:
      summary: Cadastrar um novo aluno.
      tags:
        - Aluno
      operationId: cadastrar_aluno
      parameters:
        - in: body
          name: body
          description: Modelo de Aluno
          required: true
          schema:
            $ref: "#/definitions/Aluno"
      responses:
        '201':
          description: Criado (Created)
          schema:
            $ref: "#/definitions/GeneralResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      summary: Listar todos os alunos.
      tags:
        - Aluno
      operationId: listar_alunos
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/AlunosResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aluno/media:
    x-swagger-router-controller: aluno
    get:
      summary: Filtrar todas as notas dos alunos com base na media geral.
      tags:
        - Nota
      operationId: listar_alunos_acima_media
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/AlunosResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aluno/{aluno_id}:
    x-swagger-router-controller: aluno
    put:
      summary: Atualizar/criar um aluno.
      tags:
        - Aluno
      operationId: atualizar_aluno
      parameters:
        - in: path
          name: aluno_id
          description: Índice de Aluno
          required: true
          type: integer
        - in: body
          name: body
          description: Modelo de Aluno
          required: true
          schema:
            $ref: "#/definitions/AlunoPut"
      responses:
        '201':
          description: Criado ou modificado (Created)
          schema:
            $ref: "#/definitions/GeneralResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      summary: Listar um aluno.
      tags:
        - Aluno
      operationId: listar_aluno
      parameters:
        - in: path
          name: aluno_id
          description: Índice de Aluno
          required: true
          type: integer
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/AlunoResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aluno/{aluno_id}/endereco:
    x-swagger-router-controller: aluno
    get:
      summary: Listar endereços de um aluno.
      tags:
        - Endereço
      operationId: listar_enderecos_aluno
      parameters:
        - in: path
          name: aluno_id
          description: Índice de Aluno
          required: true
          type: integer
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/EnderecoResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /aluno/{nota}/criterio/{criterio}:
    x-swagger-router-controller: aluno
    get:
      summary: Filtrar (< ou >) todas as notas dos alunos.
      tags:
        - Nota
      operationId: listar_notas_alunos
      parameters:
        - in: path
          name: nota
          description: Nota de Aluno
          required: true
          type: number
        - in: path
          name: criterio
          description: Filtro de notas dos alunos (< ou >)
          required: true
          type: string
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/AlunosResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"

  /endereco:
    x-swagger-router-controller: endereco
    post:
      summary: Cadastrar um novo endereço.
      tags:
        - Endereço
      operationId: cadastrar_endereco
      parameters:
        - in: body
          name: body
          description: Modelo de Endereço
          required: true
          schema:
            $ref: "#/definitions/Endereco"
      responses:
        '201':
          description: Criado (Created)
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      summary: Listar todos os endereços.
      tags:
        - Endereço
      operationId: listar_enderecos
      responses:
        '200':
          description: Sucesso (OK)
          schema:
            $ref: "#/definitions/EnderecosResponse"
        '400':
          description: Requisição Inválida (Bad Request)
          schema:
            $ref: "#/definitions/ErrorResponse"
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
          schema:
            $ref: "#/definitions/ErrorResponse"


  /docs:
    x-swagger-pipe: swagger_raw

definitions:
  Aluno:
    type: object
    properties:
      nome:
        type: string
      data_nascimento:
        type: string
        format: date
      cpf:
        type: string
      nota:
        type: number
    required:
      - nome
      - data_nascimento
      - cpf
      - nota

  AlunoPut:
    type: object
    properties:
      nome:
        type: string
      data_nascimento:
        type: string
        format: date
      cpf:
        type: string
      nota:
        type: number

  AlunoResponse:
    type: object
    properties:
      nome:
        type: string
      data_nascimento:
        type: string
        format: date
      cpf:
        type: string
      nota:
        type: number
    required:
      - nome
      - data_nascimento
      - cpf
      - nota

  AlunosResponse:
    type: array
    items:
      type: object
      properties:
        nome:
          type: string
        data_nascimento:
          type: string
          format: date
        cpf:
          type: string
        nota:
          type: number
      required:
        - nome
        - data_nascimento
        - cpf
        - nota

  Endereco:
    type: object
    properties:
      rua:
        type: string
      numero:
        type: string
      complemento:
        type: string
      bairro:
        type: string
    required:
      - rua
      - bairro

  EnderecoResponse:
    type: object
    properties:
      endereco:
        type: string
      bairro:
        type: string
    required:
      - endereco
      - bairro

  EnderecosResponse:
    required:
      - total
      - enderecos
    properties:
      total:
        type: integer
      enderecos:
        type: array
        items:
          type: object
          properties:
            endereco:
              type: string
            bairro:
              type: string
          required:
            - endereco
            - bairro

  GeneralResponse:
    type: object
    properties:
      success:
        type: integer
        description: returns 1 if successful
      description:
        type: string
        description: a short comment
    required:
      - success
      - description

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string